name: Perform Tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install
        uses: borales/actions-yarn@v4
        with:
          cmd: install # will run `yarn install` command

      - name: Lint
        uses: borales/actions-yarn@v4
        with:
          cmd: lint # will run `yarn lint` command

      - name: Check Format
        uses: borales/actions-yarn@v4
        with:
          cmd: fmt:check # will run `yarn fmt:check` command

  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install
        uses: borales/actions-yarn@v4
        with:
          cmd: install

      - name: Typecheck
        uses: borales/actions-yarn@v4
        with:
          cmd: tsc

      - name: Run Tests
        uses: borales/actions-yarn@v4
        with:
          cmd: test.run

  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install
        uses: borales/actions-yarn@v4
        with:
          cmd: install

      - name: Build
        uses: borales/actions-yarn@v4
        with:
          cmd: build.client
